### PR TITLE
Add brocfile option to override default brocfile name

### PR DESCRIPTION
**Pull request by lord**
This adds the option to load a `Brocfile` with a specified name. Useful if you have multiple `Brocfile`s you want to build with a single `Gruntfile`.

### CODE REVIEW

**Comment by SlexAxton** [comment]
Ping on this. Wouldn't mind this getting in.

**Comment by SlexAxton** [comment]
Noticed a conflict now, resolved at: https://github.com/ericf/grunt-broccoli-build/pull/6

**Comment by ericf** [comment]
This is in `v0.5.0`.

**Comment by SlexAxton** [comment]
I can make another issue, but I'm mobile. We also need to switch the 'ncp'
dependency to ember-cli-ncp. ncp has version sniffs that break io.js (issue
79 I think on ncp). Stefan is maintaining one with fixes for ember cli so
that's a good drop in (it just the same code with a few fixes).

(I went on a 7 hour bug hunt last night because grunt-broccoli-build was
hanging with 15 or so files. Turned out to be ncp's fault + iojs version)

**Comment by ericf** [comment]
@SlexAxton I updated to the latest version of `ncp` if that doesn't fix the issue, then let's switch to @stefanpenner's fork.

**Comment by SlexAxton** [comment]
It does not fix the issue as of 8:30am this morning. (Its entirely
unmaintained)

**Pull request merged**
